### ISSUE TITLE
Initial Milestone

### ISSUE THREAD

**Issue by l0rd** [che-incubator/chectl#1]
- [x] server:start (with fresh stopped minikube + helm)
- [ ] server:start add basic flags: 
  - [x] custom image
  - [x] multi-user
  - [x] https
  - [ ] pvc strategy
  - [x] namespace
- [x] server:stop 
- [ ] improve error messages: title / description / fix / url
- [ ] workspace:start with flags 
  - [x] --workspaceconfig 
  - [x] --devfile 
  - [ ] --stack --example
- [ ] workspace:stop
- [ ] workspace:list
- [ ] server:update
- [ ] server:update --localassemblypath

**Comment by sleshchenko** [comment]
Looks like it's a bit outdated. @l0rd Does it make sense to keep it open?
